'use client'

import { useState, useEffect } from 'react'
import { AppLayout } from '@/components/layout/AppLayout'
import { MobileNavigation, BottomTabNavigation } from '@/components/mobile/MobileNavigation'
import { useIsMobile } from '@/hooks/use-mobile'
import { PoweredByEaseCloud } from '@/components/PoweredByEaseCloud'
import Link from 'next/link'
import { fetchReports, UiReport } from '@/lib/localApi'

export default function MainPage() {
  const [reports, setReports] = useState<UiReport[]>([])
  const [loading, setLoading] = useState(true)
  const isMobile = useIsMobile()

  useEffect(() => {
    fetchReports()
      .then(setReports)
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [])

  const content = (
    <div className="pt-8 pb-16 px-4 max-w-2xl mx-auto">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 sm:text-5xl">
          Magento{' '}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-600 to-red-600">
            Performance
          </span>
          {' '}Reports
        </h1>
        <p className="mt-6 text-lg text-gray-600 leading-7">
          View and explore performance reports generated by the{' '}
          <code className="bg-gray-100 px-1 py-0.5 rounded text-sm font-mono text-gray-800">mageperf</code>{' '}
          CLI tool.
        </p>
      </div>

      {/* CLI instructions */}
      <div className="mt-10 bg-gray-900 rounded-xl p-6 text-left shadow-xl">
        <p className="text-gray-400 text-sm mb-3 font-medium">Run an analysis from your terminal:</p>
        <pre className="text-green-400 font-mono text-sm overflow-x-auto">
          {`$ mageperf analyze https://your-store.example.com`}
        </pre>
        <p className="text-gray-500 text-xs mt-3">
          Then refresh this page to see the new report.
        </p>
      </div>

      {/* Recent reports */}
      <div className="mt-10">
        {loading ? (
          <div className="text-center py-8">
            <div className="w-6 h-6 border-2 border-orange-500 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
            <p className="text-gray-500 text-sm">Loading reports...</p>
          </div>
        ) : reports.length === 0 ? (
          <div className="text-center py-8 bg-white rounded-xl border border-gray-200 shadow-sm">
            <p className="text-gray-500">No reports yet.</p>
            <p className="text-gray-400 text-sm mt-1">
              Run <code className="bg-gray-100 px-1 rounded font-mono">mageperf analyze &lt;url&gt;</code> to generate your first report.
            </p>
          </div>
        ) : (
          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Recent Reports</h2>
            <div className="space-y-3">
              {reports.slice(0, 5).map(r => (
                <Link
                  key={r.task_id}
                  href={`/report/${r.task_id}`}
                  className="flex items-center justify-between bg-white rounded-xl border border-gray-200 px-5 py-4 hover:shadow-md hover:border-orange-300 transition-all"
                >
                  <div>
                    <p className="font-medium text-gray-900 truncate max-w-xs">
                      {(() => { try { return new URL(r.report_data.url).hostname } catch { return r.report_data.url } })()}
                    </p>
                    <p className="text-sm text-gray-500 mt-0.5">
                      {new Date(r.created_at.$date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className={`text-2xl font-bold ${
                      (r.report_data.summary?.overall_score ?? 0) >= 80 ? 'text-emerald-600' :
                      (r.report_data.summary?.overall_score ?? 0) >= 60 ? 'text-amber-600' :
                      'text-red-600'
                    }`}>
                      {(r.report_data.summary?.overall_score ?? 0).toFixed(0)}
                    </span>
                    <span className="text-gray-400 text-sm">→</span>
                  </div>
                </Link>
              ))}
            </div>
            {reports.length > 5 && (
              <div className="text-center mt-4">
                <Link href="/all-analysis" className="text-orange-600 hover:text-orange-700 text-sm font-medium">
                  View all {reports.length} reports →
                </Link>
              </div>
            )}
          </div>
        )}
      </div>

      <div className="mt-12">
        <PoweredByEaseCloud variant="compact" className="py-4" />
      </div>
    </div>
  )

  if (isMobile) {
    return (
      <div className="flex flex-col h-screen bg-gradient-to-br from-orange-50 via-white to-red-50 relative">
        <MobileNavigation />
        <main className="flex-1 overflow-y-auto smooth-scroll thumb-zone">
          {content}
        </main>
        <BottomTabNavigation />
      </div>
    )
  }

  return (
    <AppLayout className="bg-gradient-to-br from-orange-50 via-white to-red-50">
      {content}
    </AppLayout>
  )
}
